//! `SeaORM` Entity. Generated by sea-orm-codegen 0.10.2

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "member_info")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i64,
    pub active: i8,
    pub created_at: Option<DateTimeUtc>,
    pub created_id: i64,
    pub updated_at: Option<DateTimeUtc>,
    pub updated_id: Option<i64>,
    pub username: String,
    pub display_name: String,
    pub password: Option<String>,
    pub sign_up_type: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
