//! `SeaORM` Entity. Generated by sea-orm-codegen 0.10.2

use sea_orm::entity::prelude::*;
use serde::{Serialize, Deserialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "post")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i64,
    pub active: i8,
    pub created_at: Option<DateTime>,
    pub created_id: Option<i64>,
    pub updated_at: Option<DateTime>,
    pub updated_id: Option<i64>,
    pub title: String,
    #[sea_orm(column_type = "Text")]
    pub body: String,
    pub published: i8,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
